name: Continuous integration

on:
  # Manual dispatch for testing
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build construo
        run: ./gradlew assemble
        working-directory: ./construo
      - name: Build test project
        run: ./gradlew test:packageLinuxX64 test:packageMacM1 test:packageMacX64 test:packageWinX64
      - name: Artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: outputs-${{ matrix.os }}
          path: test/build/construo/dist
          retention-days: 1
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Check code formatting construo
        run: ./gradlew spotlessCheck
        working-directory: ./construo
      - name: Check code formatting test project
        run: ./gradlew spotlessCheck
